In [19]:
import pandas as pd

sales = pd.DataFrame({
    "order_id": ["O001", "O002", "O003", "O003", "O005", "O006"],
    "product": ["Laptop", "Mouse", "Keyboard", "Keyboard", "Monitor", "Laptop"],
    "quantity": ["2", "5", "0", "-1", "3", "4"],
    "unit_price": ["50000", "500", "0", "-100", "15000", "55000"],
    "payment_method": [
        "UPI",
        "upi",
        "Credit Card",
        "credit card",
        "COD",
        None
    ],
    "order_date": [
        "2025-01-10",
        "10-02-2025",
        "2025/03/15",
        "2025/03/15",
        "2025-04-20",
        "2025-99-99"
    ]
})

In [2]:
sales

  order_id   product quantity unit_price payment_method  order_date
0     O001    Laptop        2      50000            UPI  2025-01-10
1     O002     Mouse        5        500            upi  10-02-2025
2     O003  Keyboard        0          0    Credit Card  2025/03/15
3     O003  Keyboard       -1       -100    credit card  2025/03/15
4     O005   Monitor        3      15000            COD  2025-04-20
5     O006    Laptop        4      55000            NaN  2025-99-99

In [3]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        6 non-null      str
 1   product         6 non-null      str
 2   quantity        6 non-null      str
 3   unit_price      6 non-null      str
 4   payment_method  5 non-null      str
 5   order_date      6 non-null      str
dtypes: str(6)
memory usage: 420.0 bytes

In [4]:
sales.isnull().sum()

order_id          0
product           0
quantity          0
unit_price        0
payment_method    1
order_date        0
dtype: int64

In [20]:
(sales.isnull().mean()*100).round(2)

order_id           0.00
product            0.00
quantity           0.00
unit_price         0.00
payment_method    16.67
order_date         0.00
dtype: float64

In [6]:
sales.duplicated().sum()

np.int64(0)

In [21]:
sales[sales.duplicated(subset="order_id",keep=False)]

  order_id   product quantity unit_price payment_method  order_date
2     O003  Keyboard        0          0    Credit Card  2025/03/15
3     O003  Keyboard       -1       -100    credit card  2025/03/15

In [22]:
#convert quantity and unit price into numeric

sales["quantity"]=pd.to_numeric(sales["quantity"],errors="coerce")
sales["unit_price"]=pd.to_numeric(sales["unit_price"],errors="coerce")
sales["order_date"]=pd.to_datetime(sales["order_date"],errors="coerce")

In [23]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        6 non-null      str
 1   product         6 non-null      str
 2   quantity        6 non-null      int64
 3   unit_price      6 non-null      int64
 4   payment_method  5 non-null      str
 5   order_date      2 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(2), str(3)
memory usage: 420.0 bytes

In [24]:
sales

  order_id   product  quantity  unit_price payment_method order_date
0     O001    Laptop         2       50000            UPI 2025-01-10
1     O002     Mouse         5         500            upi        NaT
2     O003  Keyboard         0           0    Credit Card        NaT
3     O003  Keyboard        -1        -100    credit card        NaT
4     O005   Monitor         3       15000            COD 2025-04-20
5     O006    Laptop         4       55000            NaN        NaT

In [25]:
sales.loc[sales["quantity"].le(0),"quantity"]=pd.NA

sales.loc[sales["quantity"].le(0),"quantity"] = pd.NA

In [26]:
sales

  order_id   product  quantity  unit_price payment_method order_date
0     O001    Laptop       2.0       50000            UPI 2025-01-10
1     O002     Mouse       5.0         500            upi        NaT
2     O003  Keyboard       NaN           0    Credit Card        NaT
3     O003  Keyboard       NaN        -100    credit card        NaT
4     O005   Monitor       3.0       15000            COD 2025-04-20
5     O006    Laptop       4.0       55000            NaN        NaT