In [1]:
import pandas as pd

customer = pd.DataFrame({
    "customer_id": ["C001", "C002", "C003", "C004", "C005"],
    "name": ["Ravi", "Priya", "Kumar", "Ravi", "Anita"],
    "age": ["35", "Unknown", "?", "-5", "53.0"],
    "gender": ["Male", "female", "M", "MALE", "F"],
    "city": ["Hyderabad", "Chennai", "Hyderabad", "hyderabad", None]
})

customer

  customer_id   name      age  gender       city
0        C001   Ravi       35    Male  Hyderabad
1        C002  Priya  Unknown  female    Chennai
2        C003  Kumar        ?       M  Hyderabad
3        C004   Ravi       -5    MALE  hyderabad
4        C005  Anita     53.0       F        NaN

In [23]:
#1. age contains Unknown, ?, negative value and "53.0"

#convert age into number format

customer["age"]=pd.to_numeric(customer["age"],errors="coerce").astype("Int64")
customer.loc[~customer["age"].between(0,100),"age"]=pd.NA
customer

  customer_id   name   age  gender       city
0        C001   Ravi    35    Male  Hyderabad
1        C002  Priya  <NA>  female    Chennai
2        C003  Kumar  <NA>       M  Hyderabad
3        C004   Ravi  <NA>    MALE  hyderabad
4        C005  Anita    53       F        NaN

In [ ]:
#2.Gender has inconsistent values.


customer["gender"] = customer["gender"].replace({
    "M": "Male",
    "MALE": "Male",
    "F": "Female",
    "female": "Female"
})

customer

  customer_id   name   age  gender       city
0        C001   Ravi    35    Male  Hyderabad
1        C002  Priya  <NA>  Female    Chennai
2        C003  Kumar  <NA>    Male  Hyderabad
3        C004   Ravi  <NA>    Male  hyderabad
4        C005  Anita    53  Female        NaN

In [27]:

#3.City has inconsistent capitalization.

customer["city"]=customer["city"].str.title()
customer

#4. Missing city.

customer["city"]=customer["city"].fillna("unknown")
customer

  customer_id   name   age  gender       city
0        C001   Ravi    35    Male  Hyderabad
1        C002  Priya  <NA>  Female    Chennai
2        C003  Kumar  <NA>    Male  Hyderabad
3        C004   Ravi  <NA>    Male  Hyderabad
4        C005  Anita    53  Female    unknown

In [2]:
#5. Duplicate customer name exists, but customer_id is unique.

customer.drop_duplicates(subset=["name","age","gender","city"])

  customer_id   name      age  gender       city
0        C001   Ravi       35    Male  Hyderabad
1        C002  Priya  Unknown  female    Chennai
2        C003  Kumar        ?       M  Hyderabad
3        C004   Ravi       -5    MALE  hyderabad
4        C005  Anita     53.0       F        NaN